platform :ios, '7.0'
pod 'Google/AppInvite'

# If using CocoaPods 1.0.0+, use the new target syntax.
# target 'AppInvitesExample'
# target 'AppInvitesExampleSwift'
# target 'AppInvitesExampleTests'

# and delete the link_with command.
link_with 'AppInvitesExample', 'AppInvitesExampleSwift', 'AppInvitesExampleTests'
