# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'appinvites' do
  platform :ios, '6.0'
  source 'sso://cpdc-internal/spec.git'
  pod 'GPPInvite', '~> 1.0.0'
end

target 'appinvitesTests' do

end

