# source 'https://cpdc-eap.googlesource.com/spec.git'
source 'sso://cpdc-eap/spec.git'

# AnalyticsExample
platform :ios, '7.0'
pod 'Google/Analytics'
link_with 'AnalyticsExample', 'AnalyticsExampleSwift', 'AnalyticsExampleTests'
