platform :ios, '7.0'
pod 'Google/AdMob'

# If using CocoaPods 1.0.0+, use the new target syntax.
# target 'AdMobExample'
# target 'AdMobExampleSwift'
# target 'AdMobExampleTests'
# target 'AdMobExampleSwiftTests'

# and delete the link_with command.
link_with 'AdMobExample', 'AdMobExampleSwift', 'AdMobExampleTests', 'AdMobExampleSwiftTests'