source 'https://cpdc-eap.googlesource.com/spec.git'

platform :ios, '7.0'
pod 'Google/AdMob', '~> 1.0.0'

link_with 'AdMobExample', 'AdMobExampleSwift', 'AdMobExample Tests', 'AdMobExampleSwift Tests'
